languageCode: "en-us"
baseUrl: "https://ovdixon.com"
title: "Oliver Dixon"
theme: "anubis"
paginate: 10
googleAnalyticsID: G-19YEDHDYJC
enableRobotsTXT: true


menu:
  main:
  - identifier: projects
    name: Projects
    title: Projects
    url: /
    weight: 0
  - identifier: about
    name: About
    title: About
    url: /about
    weight: 0

params:
  author: "Oliver Dixon"
  description: ""
  customCSS: ["css/my.css"]
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light-without-switcher
  readMore: false

markup:
  goldmark:
    renderer:
        unsafe: true # enable raw HTML in Markdown